### ISSUE TITLE
Failed Precondition - Intent with ID not found among intents in environment 

### ISSUE THREAD

**Issue by Archetype90** [googleapis/dialogflow-python-client-v2#171] opened 2019-12-27 16:08 UTC
#### Environment details

1. Windows 10
2. Python 3.6.6
3. dialogflow version: 0.7.2`

#### Steps to reproduce

It is not clear to me what caused this issue to pop up. Existing code that has not changed gets this error intermittently starting about three days ago. I am roughly using the boilerplate stream audio and print the intermediate transcript code. 

After I stop speaking, but before an intent is returned, I get the following exception:

```
2019-12-27 09:56:46 - INFO - Intermediate transcript: "turn the display".
2019-12-27 09:56:46 - ERROR - 400 Intent with id 'xxxxxxxxxxxxxxxxxxxxxxxxx' not found among intents in environment '' for agent with id 'xxxxxxxxxxxxxxxxxxxxxxxxx'.
com.google.apps.framework.request.StatusException: <eye3 title='FAILED_PRECONDITION'/> generic::FAILED_PRECONDITION: Intent with id 'xxxxxxxxxxxxxxxxxxxxxxxxx' not found among intents in environment '' for agent with id 'xxxxxxxxxxxxxxxxxxxxxxxxx'.
2019-12-27 09:56:46 - ERROR - Failed precondition - what does this mean?
====================
2019-12-27 09:56:46 - INFO - Query text:
2019-12-27 09:56:46 - INFO - Detected intent:  (confidence: 0.0)
2019-12-27 09:56:46 - INFO - Fulfillment text:
```

The error is very explicit, but the error is not consistent and the intents do exist in my project. 

#### Stack trace
```
2019-12-27 09:52:13 - INFO - Intermediate transcript: "turn the display".
Exception in thread Thread-15:
Traceback (most recent call last):
  File "C:\Users\wbaker\AppData\Local\Programs\Python\Python36\lib\site-packages\google\api_core\grpc_helpers.py", line 79, in next
    return six.next(self._wrapped)
  File "C:\Users\wbaker\AppData\Local\Programs\Python\Python36\lib\site-packages\grpc\_channel.py", line 388, in __next__
    return self._next()
  File "C:\Users\wbaker\AppData\Local\Programs\Python\Python36\lib\site-packages\grpc\_channel.py", line 382, in _next
    raise self
grpc._channel._Rendezvous: <_Rendezvous of RPC that terminated with:
        status = StatusCode.FAILED_PRECONDITION
        details = "Intent with id 'xxxxxxxxxxxxxxxxxxxxxxxxx' not found among intents in environment '' for agent with id 'xxxxxxxxxxxxxxxxxxxxxxxxx'.
com.google.apps.framework.request.StatusException: <eye3 title='FAILED_PRECONDITION'/> generic::FAILED_PRECONDITION: Intent with id 'xxxxxxxxxxxxxxxxxxxxxxxxx' not found among intents in environment '' for agent with id 'xxxxxxxxxxxxxxxxxxxxxxxxx'."
        debug_error_string = "{"created":"@1577461933.949000000","description":"Error received from peer ipv4:172.217.14.170:443","file":"src/core/lib/surface/call.cc","file_line":1055,"grpc_message":"Intent with id 'xxxxxxxxxxxxxxxxxxxxxxxxx' not found among intents in environment '' for agent with id 'xxxxxxxxxxxxxxxxxxxxxxxxx'.\ncom.google.apps.framework.request.StatusException: <eye3 title='FAILED_PRECONDITION'/> generic::FAILED_PRECONDITION: Intent with id 'xxxxxxxxxxxxxxxxxxxxxxxxx' not found among intents in environment '' for agent with id 'xxxxxxxxxxxxxxxxxxxxxxxxx'.","grpc_status":9}"
>
```

I suspect there is a decent chance that I am doing something wrong here, but the fact that I had not seen this error for 1-2 months while using the same code has me concerned that this is some sort of bug.

**Comment by Syndace** [comment] 2020-01-13 14:47
I'm experiencing the same issue. Some code that was working just a while ago now throws errors as described by @Archetype90 during intent classification. Note that I am doing text-based intent classification and not speech-based.

It might be important to add that I programmatically train the agent before trying to classify inputs.

I had a similar issue back when initially writing the code a few months ago, back then the issue was me not waiting for the training to finish. But now I am quite sure that I do in fact wait for the training to finish.

I found something weird in the web interface: When looking under "Intents", the web interface tells me "No regular intents yet. Create the first one.". This is expected, as I have removed all intents from the Agent. When clicking on "Validation" though, it shows a list of intent ids, saying "Intent 'xxx' contains no training phrases.". This makes me believe that the intent ids somehow remain in the system, even though the intents should have been completely removed.
Maybe this is related to the issues we are experiencing?

**Comment by nnegrey** [comment] 2020-01-15 18:19
Hi folks, can you provide some more information about what you are doing?

Are you using V2 or V2Beta1? 
Do you have environments configured or No?
Can you point to some code or share a bit of code to help re-produce the issue?

**Comment by Syndace** [comment] 2020-01-16 11:01
Oh yeah, the API version would've been a good idea.

1. I'm on V2 (not beta).
2. Probably not, because I have no idea what you mean by "environment".
3. Following are a few quick code snippets I copied from my code. I don't really have the time to prepare a minimal example right now, sorry.

```Python
import dialogflow_v2

# Prepare the various clients (credentials are provided via the env var)
agents_client   = dialogflow_v2.AgentsClient()
intents_client  = dialogflow_v2.IntentsClient()
sessions_client = dialogflow_v2.SessionsClient()

# Create/configure the agent
agents_client.set_agent(dialogflow_v2.types.Agent(...))

# Create a few intents, each with multiple dialogflow_v2.types.Intent.TrainingPhrase
intent_instances = [ dialogflow_v2.types.Intent(...), ... ]

intent_batch = dialogflow_v2.types.IntentBatch(intents=intent_instances)

# Upload the intents
intents_client.batch_update_intents(..., intent_batch_inline=intent_batch).result()

# Train the agent
agents_client.train_agent(...).result()

for inputToClassify in inputsToClassify:
    # Prepare an input to classify
    text_input  = dialogflow_v2.types.TextInput(text=inputToClassify)
    query_input = dialogflow_v2.types.QueryInput(text=text_input)

    # Classify the input
    detect_intent_response = sessions_client.detect_intent(session, query_input)
```

When running the code like this, the call to detect_intent sometimes fails with the error message that OP posted.

**Comment by Archetype90** [comment] 2020-01-16 13:48
1. V2 (not beta)
2. As above, I am not entirely clear what an environment is (can you link documentation?)
3. I am using fairly boilerplate code from your examples of detecting an intent with stream, with modifications around the intent detection. This can be found here: https://cloud.google.com/dialogflow/docs/detect-intent-stream

My try/except block (which generates the error in the OP) is this:

        print('=' * 20)
        try:
            for response in responses:
                self.logger.info('Intermediate transcript: "{}".'.format(
                    response.recognition_result.transcript))
        except google_exceptions.FailedPrecondition as ex:
            self.logger.error(ex)
            self.logger.error("Failed precondition - what does this mean?")

**Comment by nnegrey** [comment] 2020-01-16 22:33
On the environment front, I'll also assume no, I just asked cus I saw it pop up in your stack trace. 

But it is a beta feature right now: https://cloud.google.com/dialogflow/docs/agents-versions

I haven't had as much time today, but I'll try to take a look more tomorrow.

**Comment by nnegrey** [comment] 2020-01-17 16:41
Other questions for @Syndace, are you uploading new intents every time then trying to detect them?

**Comment by nnegrey** [comment] 2020-01-17 16:42
@Archetype90, on our samples repo, there is a PR for a microphone streaming sample, is yours similar to this?
https://github.com/GoogleCloudPlatform/python-docs-samples/pull/2566

**Comment by Syndace** [comment] 2020-01-17 17:34
Yes, my flow is:
- create/set up the agent
- upload intents with example utterances
- train the agent
- classify some samples

All of these steps happen right after the previous one is finished, one whole iteration of that process only takes a few seconds to a minute (depending on the number of training samples and the number of samples to classify).

**Comment by nnegrey** [comment] 2020-01-17 17:46
What do you pass as the IntentID when using batchUpdate to create the intents?

**Comment by nnegrey** [comment] 2020-01-17 17:48
Also @Syndace, since you seem to start from scratch every time, have you considered just using `ImportAgentRequest`?

**Comment by Syndace** [comment] 2020-01-17 18:10
I don't think `batch_update_intents` takes any intent ids, does it?

`ImportAgentRequest` is not applicable, since the intents and utterances usually differ between runs, but thanks for the heads up.

**Comment by Syndace** [comment] 2020-01-17 18:15
In case you wonder: The code is for some type of benchmarking system, which is why we have to do automatic training and classification rapidly after each other and we can't just import/export agents.

**Comment by Syndace** [comment] 2020-01-17 19:10
I created a minimal example (which is not so "minimal" at over 100 lines lol): https://paste.debian.net/1126448/ (valid for three days)

It's not deterministic when the error exactly happens, but I have never reached the 10th iteration without encountering the error. I hope you can reproduce with that.

**Comment by Archetype90** [comment] 2020-01-17 19:30
@nnegrey Yes, my code is very similar to that example, but with slight differences due to using a wake word. So the stream is disabled until the wake word is detected, at which point it is re-enabled. 

I do want to point out that my use case is fairly similar to @Syndace. It is very likely that the intents and utterances have changed between runs, so it is quite common to delete everything in the agent and recreate all intents. That said, as Syndace said, it is not deterministic. Sometimes I will run for a few days and not see the error, but then it pops up for 10 minutes. 

I do not envy you being assigned this bug ;)

**Comment by nnegrey** [comment] 2020-01-17 22:41
I'm gonna guess some race condition is being hit on the API if having create, test, delete being constantly thrown at it. Which as far as I know, I don't think Dialogflow was meant for this type of behavior of spinning up and shutting down agents, but rather for long-standing chat bots.

I'd suggest opening an issue against the product team themselves on this page: https://cloud.google.com/support/docs/issue-trackers

But this doesn't appear to be a client library issue itself, so I'm gonna close this out.

**Comment by Syndace** [comment] 2020-01-20 09:30
Right, this is probably not an issue of the client library, thanks for your help @nnegrey and for pointing us to the DF issue tracker. I found [this issue](https://issuetracker.google.com/issues/134860227), which sounds related to what @Archetype90 and I experience.

**Comment by Syndace** [comment] 2020-01-20 16:11
I'm sorry for creating so much traffic here but I've spent another day trying things and debugging and I have news.

First of all: Disable automatic training and automatic validation (under "ML Settings") on your agents! Both are on by default and (at least the automatic training) takes considerable nondeterministic time.

With the automatic training disabled I can now encounter the `FAILED_PRECONDITION` almost guaranteed. In that new position I was able to rule out a few things and got the following results:
1. There are **no** issues with race-conditions between any of the functions _except_ for `train_agent` and `detect_intent`. The other functions (`set_agent`, `batch_update_intents`, `batch_delete_intents`) do _not_ play a role in this issue. You can confirm that by manually creating a new agent using the web frontend, disabling automatic training, adding some intents and example utterances and _only then_ running a simple Python script which just calls `train_agent` right away, followed by a few calls to `detect_intent`. You will most probably encounter the `FAILED_PRECONDITION`.
2. `train_agent` does in fact **not wait** for the training to finish but it returns instantly. You can verify that be feeding your agent with a big data set that actually takes a while to train. Now open the Dialogflow web frontend and have an eye on it while you run your `train_agent` and `detect_intent` script. The script will raise the exception long before the web frontend even shows you that the training has started, let alone finished!

Now one thing is still unclear: The RPC call [`train`](https://cloud.google.com/dialogflow/docs/reference/rest/v2/projects.agent/train), which is the basis for the `train_agent` method, returns an `Operation`. The question is: does that `Operation` resolve too early, which would make all of this a server-side issue, or does the client-side code not wait for the `Operation` to resolve correctly?

Please @nnegrey, try to find out whether it's the server-side that resolves the `Operation` too early or it's this library which doesn't wait for the `Operation` correctly.

I also prepared [a new version of my script](https://paste.debian.net/1126832/) which is reduced to only what's required to reproduce. Please create a new agent using the web frontend and disable both automatic training and automatic validation on it. Then fill the `TODO` values at the top of my script. Now when running the script you should encounter the exception almost guaranteed.

**Comment by Archetype90** [comment] 2020-01-21 13:12
Thanks for your help @nnegrey. 

That is a great find @Syndace. I will be very curious to hear how and where the Operation is handled.

**Comment by nnegrey** [comment] 2020-01-27 21:52
I can only reproduce this when intents are deleted, then new ones are added, then I get the error message.

**Comment by nnegrey** [comment] 2020-01-27 22:54
I've passed this along for the team to investigate. I don't believe this is library related.

**Closed by nnegrey** 2020-01-27 22:54 UTC
Labels: :rotating_light:, needs more info, triage me

**Comment by Archetype90** [comment] 2020-01-28 15:20
Thank you @nnegrey 

Were you able to verify what was wrong with the Operation returning immediately? Should I open a new ticket for that issue? I believe that Operation should not immediately return done, whether or not it would fix this issue is another question.

**Comment by Syndace** [comment] 2020-01-29 12:01
Thanks @nnegrey, I also can't reproduce any more, which confirms that it's probably not a bug in the client library. I'll go ahead and bug Dialogflow itself if the issue ever appears again.

**Comment by luddilo** [comment] 2020-02-23 10:44
@Syndace did you encounter the error again? I started getting the error (using the NodeJS library) after boosting the performance of the runtime making the calls, essentially making the calls (train, detectIntent) in more rapid succession. So, indeed, it appears to be some latency after train() calls before detectIntent() can be called.

**Comment by Syndace** [comment] 2020-02-23 10:54
@luddilo sorry, I didn't encounter it again after it disappeared over night. If you make any progress please keep me up to date though! I kind of expect the issue to re-appear any day.

**Comment by nnegrey** [comment] 2020-02-24 17:36
One way to help mitigate this is to use the beta version with environments, especially if your use case involves constant changes to the agent. 

You'll want to disable automatic training and create a "dev" environment and "production" environment. 
https://cloud.google.com/dialogflow/docs/agents-versions

**Comment by shnippi** [comment] 2020-08-13 14:09
Hi ive come to this problem twice now, and yes all of the informations above are correct. However, if youre just looking to fix this problem there is a way easier solution. On your dialogflow webagent, all you need to do is do a backup from your current version, (in import/export settings, it downloads a zip to your pc). And then simply import and overwrite the agent again. This fixed it for me multiple times now. Hope this helps anyone encountering this problem as well.

**Comment by nicolas-lair** [comment] 2020-11-29 21:48
Hi I also randomly encounter this issue. @shnippi 's trick worked for me.
