### ISSUE TITLE
Reason for retry is not given in debug output

### ISSUE THREAD

**Issue by Syndace** [googleapis/dialogflow-python-client-v2#174] opened 2020-01-20 13:21 UTC
I'm having a bit of trouble with the retry/timeout behaviour of `train_agent` currently. To debug that, I configured my log level to debug and I get the following output:
```
DEBUG:google.api_core.retry:Retrying due to , sleeping 0.6s ...
DEBUG:google.api_core.retry:Retrying due to , sleeping 3.7s ...
```
Needless to say that the `due to ,` part is a little unsatisfying and not too helpful :D

I'm using V2 (not beta) on Linux, using the most recent version of the library on pip (`0.7.2`) for Python 3.7.

No special steps are needed to reproduce. Just prepare an agent with a few intents and some example utterances, create a Python script and set the log level of `logging` to `DEBUG` and call `train_agent` on that agent. You will most likely get at least one of the log lines above.

**Comment by czahedi** [comment] 2020-02-03 19:49
Hey @nnegrey have you had a chance to check this out?

**Comment by nnegrey** [comment] 2020-02-10 17:48
I'm not able to reproduce:

# Code
```
import logging
import os

import dialogflow

PROJECT_ID = os.environ['GCLOUD_PROJECT']

logging.basicConfig(filename='example.log', level=logging.DEBUG)

client = dialogflow.AgentsClient()
parent = client.project_path(PROJECT_ID)
operation = client.train_agent(parent=parent)
result = operation.result()
print(type(result))
```

# Output:
```
<class 'google.protobuf.empty_pb2.Empty'>
```

# log file
```
DEBUG:google.auth.transport.requests:Making request: POST https://accounts.google.com/o/oauth2/token
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): accounts.google.com:443
DEBUG:urllib3.connectionpool:https://accounts.google.com:443 "POST /o/oauth2/token HTTP/1.1" 200 None
```

**Comment by nnegrey** [comment] 2020-02-10 17:57
Looks like the log you are seeing is thrown here: https://github.com/googleapis/python-api-core/blob/master/google/api_core/retry.py#L213

But seems like the above line isn't getting set.
https://github.com/googleapis/python-api-core/blob/master/google/api_core/retry.py#L191

If you try to output that Exception, what do you get?

**Comment by czahedi** [comment] 2020-02-14 16:37
Hey @Syndace! Hope you're well. Have you had a chance to look at Noah's notes?

**Comment by Syndace** [comment] 2020-02-15 10:45
Hi! Sorry, I haven't looked at it yet. I'll find out what the type of that exception is, it probably overrides `__str__` in a weird way.

**Comment by Syndace** [comment] 2020-02-17 16:41
As per usual the behaviour of Dialogflow has changed over night, I can't trigger the log line any more like I used to when I opened this issue. I still got it once but didn't have the required code to debug the exception in the file yet. I'll just leave the modifications in the file and tell you when I stumple upon it again.

**Comment by nnegrey** [comment] 2020-02-18 16:34
Closing for now. Feel free to file a new issue if it pops up again or comment here and reopen.

**Closed by nnegrey** 2020-02-18 16:34 UTC
Labels: :rotating_light:, api: dialogflow, triage me

**Comment by TH-eMundo** [comment] 2020-03-11 12:36
Today I encounter the log line en masse again, the exception is a `google.api_core.future.polling._OperationNotComplete`, which in fact does not provide a `__str__` (or anything on that matter).

**Comment by nnegrey** [comment] 2020-03-12 14:55
@busunkim96, do you know much about how the client libraries do logging? or who might?

**Comment by busunkim96** [comment] 2020-03-16 18:18
I do not, but logging does belong to Yoshi Core. Do you have something in particular you'd like me to investigate? @nnegrey

**Comment by nnegrey** [comment] 2020-03-17 16:06
Some info in the logs doesn't get set, see comment: https://github.com/googleapis/dialogflow-python-client-v2/issues/174#issuecomment-584250828
